import test from 'node:test';import assert from 'node:assert/strict';
import {createCombatFocusRuntime,stepCombatFocusRuntime,combatFocusCameraOptions,combatFocusReadabilityContext,renderCombatFocus} from '../src/game/CombatFocusIntegration.js';
import {dynamicParticleBudget,readabilityPolicy} from '../src/game/PresentationPolish.js';
function fakeCanvas(){const calls=[];const grad={addColorStop(){}};const ctx={calls,save(){},restore(){},fillRect(){calls.push(['fillRect']);},createRadialGradient(){return grad;},beginPath(){},arc(...a){calls.push(['arc',...a]);},stroke(){calls.push(['stroke']);},moveTo(){},lineTo(){},closePath(){},fill(){calls.push(['fill']);},globalCompositeOperation:'source-over'};return {width:1920,height:1080,getContext(){return ctx;},ctx};}
const player={x:500,y:720};const boss={id:'boss',type:'guardian',x:900,y:720,state:'windup',threatProgress:.85,parryable:true};
test('runtime initializes',()=>{const r=createCombatFocusRuntime();assert.equal(r.feel.moment.type,null);assert.equal(r.threat.target,null);});
test('step drives cue and threat together',()=>{const r=stepCombatFocusRuntime(createCombatFocusRuntime(),.016,{cue:'PERFECT PARRY · J COUNTER',enemies:[boss],player,bossMode:true});assert.equal(r.feel.moment.type,'parry');assert.equal(r.threat.targetId,'boss');});
test('camera options merge moment and threat',()=>{let r=stepCombatFocusRuntime(createCombatFocusRuntime(),.016,{cue:'PERFECT DODGE · J COUNTER',enemies:[boss],player,bossMode:true});r=stepCombatFocusRuntime(r,.016,{cue:'PERFECT DODGE · J COUNTER',enemies:[boss],player,bossMode:true});const o=combatFocusCameraOptions(r,{bossMode:true});assert.equal(o.focusX,900);assert.ok(o.followMultiplier>1);});
test('readability context exports threat intensity',()=>{const r=stepCombatFocusRuntime(createCombatFocusRuntime(),.016,{enemies:[boss],player,bossMode:true});const c=combatFocusReadabilityContext(r,{boss:true,threatCount:1});assert.ok(c.threatIntensity>0);});
test('high threat trims decorative particle budget',()=>assert.ok(dynamicParticleBudget({mode:'combat',threatCount:3,threatIntensity:.9})<dynamicParticleBudget({mode:'combat',threatCount:3,threatIntensity:0})));
test('final strike still reserves large budget',()=>assert.ok(dynamicParticleBudget({mode:'boss',moment:'finalStrike',threatCount:7,threatIntensity:1})>=106));
test('readability policy reduces fx under threat',()=>assert.equal(readabilityPolicy({mode:'combat',threatIntensity:.8}).reduceDecorativeFx,true));
test('render returns spatial anchor',()=>{let r=stepCombatFocusRuntime(createCombatFocusRuntime(),.016,{cue:'FINAL STRIKE · TEST',enemies:[boss],player,bossMode:true});r={...r,feel:{...r.feel,moment:{...r.feel.moment,time:.12}}};const c=fakeCanvas();const out=renderCombatFocus(c,r,{player,camera:{x:0,y:0,zoom:1}});assert.ok(out.anchor.x>500);assert.equal(out.momentDrawn,true);});
test('final strike suppresses threat overlay',()=>{let r=stepCombatFocusRuntime(createCombatFocusRuntime(),.016,{cue:'FINAL STRIKE · TEST',enemies:[boss],player,bossMode:true});r={...r,feel:{...r.feel,moment:{...r.feel.moment,time:.12}}};const out=renderCombatFocus(fakeCanvas(),r,{player,camera:{x:0,y:0,zoom:1}});assert.equal(out.threatDrawn,false);});
test('ordinary urgent threat can render without moment',()=>{const r=stepCombatFocusRuntime(createCombatFocusRuntime(),.016,{enemies:[boss],player,bossMode:true});const out=renderCombatFocus(fakeCanvas(),r,{player,camera:{x:0,y:0,zoom:1}});assert.equal(out.threatDrawn,true);});
test('story suppresses threat overlay',()=>{const r=stepCombatFocusRuntime(createCombatFocusRuntime(),.016,{enemies:[boss],player,bossMode:true});const out=renderCombatFocus(fakeCanvas(),r,{player,camera:{x:0,y:0,zoom:1},story:true});assert.equal(out.threatDrawn,false);});
test('reduced motion still returns active moment safely',()=>{let r=stepCombatFocusRuntime(createCombatFocusRuntime(),.016,{cue:'PERFECT DODGE',enemies:[boss],player});r={...r,feel:{...r.feel,moment:{...r.feel.moment,time:.08}}};const out=renderCombatFocus(fakeCanvas(),r,{player,camera:{x:0,y:0,zoom:1},reducedMotion:true});assert.equal(out.momentDrawn,true);});
