import test from 'node:test';
import assert from 'node:assert/strict';
import {createCombatFlowRuntime,beginCombatFlowFrame,endCombatFlowFrame,registerCombatFlowHit,clearCombatFlowHit,resetCombatFlowRuntime,combatFlowCameraOptions,combatFlowReadabilityContext,combatFlowDebug} from '../src/game/CombatFlowRuntime.js';

const raw=(pressed=[])=>({justPressed:a=>pressed.includes(a),isDown:()=>false,justReleased:()=>false});
const player=(extra={})=>({hp:320,onGround:true,dash:0,dodgeWindow:0,airDashActive:0,reaction:{state:'ready'},recovery:{state:'ready'},combat:{attack:null,attackTime:0,counterWindow:0,parryTimer:0,queuedLight:false,...extra.combat},...extra});
const lightData={startup:.08,active:.1,recovery:.3,cancelStart:.27,cancelEnd:.47,duration:.48,damage:28};

test('unified runtime starts save-free and inert',()=>{const r=createCombatFlowRuntime();assert.equal(r.hitConfirm.active,false);assert.equal(r.control.leased,null);assert.equal(r.focus.feel.moment.type,null);});
test('idle buffered light releases through unified entry point',()=>{const b=beginCombatFlowFrame(createCombatFlowRuntime(),raw(['light']),.016,{player:player(),attackData:lightData});assert.equal(b.action,'light');assert.equal(b.input.justPressed('light'),true);});
test('cue drives focus moment inside same frame',()=>{const b=beginCombatFlowFrame(createCombatFlowRuntime(),raw(),.016,{player:player(),cue:'PERFECT DODGE · J COUNTER'});assert.equal(b.momentType,'perfectDodge');});
test('registered hit confirm survives into next frame gate',()=>{let r=registerCombatFlowHit(createCombatFlowRuntime(),{attack:'light',damage:30});const b=beginCombatFlowFrame(r,raw(),.016,{player:player({combat:{attack:'light',attackTime:.25}}),attackData:lightData});assert.equal(b.runtime.hitConfirm.active,true);});
test('guarded hit is contact but not offensive boost',()=>{let r=registerCombatFlowHit(createCombatFlowRuntime(),{attack:'light',guarded:true});assert.equal(combatFlowDebug(r).hitConfirm.offensive,false);});
test('hit confirm can be cleared without resetting focus/control',()=>{let r=registerCombatFlowHit(createCombatFlowRuntime(),{attack:'light',damage:20});r=clearCombatFlowHit(r);assert.equal(r.hitConfirm.active,false);});
test('accepted frame updates control runtime after player step',()=>{let b=beginCombatFlowFrame(createCombatFlowRuntime(),raw(['light']),.016,{player:player(),attackData:lightData});const after=player({combat:{attack:'light',attackTime:.01}});const r=endCombatFlowFrame(b.runtime,player(),after);assert.equal(r.control.buffer.lastAccepted.action,'light');});
test('rejected action remains available through unified runtime',()=>{let b=beginCombatFlowFrame(createCombatFlowRuntime(),raw(['light']),.016,{player:player(),attackData:lightData});const r=endCombatFlowFrame(b.runtime,player(),player());assert.ok(r.control.buffer.entries.light);});
test('parry cue and counter window prioritize heavy',()=>{const p=player({combat:{counterWindow:.5}});const b=beginCombatFlowFrame(createCombatFlowRuntime(),raw(['light','heavy']),.016,{player:p,attackData:lightData,cue:'PERFECT PARRY · J COUNTER'});assert.equal(b.action,'heavy');});
test('dodge cue and counter window prioritize light',()=>{const p=player({combat:{counterWindow:.5}});const b=beginCombatFlowFrame(createCombatFlowRuntime(),raw(['light','heavy']),.016,{player:p,attackData:lightData,cue:'PERFECT DODGE · J COUNTER'});assert.equal(b.action,'light');});
test('camera options remain neutral without focus',()=>{const o=combatFlowCameraOptions(createCombatFlowRuntime());assert.equal(o.zoomBias,0);});
test('readability context delegates to focus runtime',()=>{const c=combatFlowReadabilityContext(createCombatFlowRuntime(),{mode:'combat',threatCount:2});assert.equal(c.mode,'combat');assert.equal(c.threatCount,2);});
test('reset clears transient control and hit confirm',()=>{let r=registerCombatFlowHit(createCombatFlowRuntime(),{attack:'light',damage:20});r=resetCombatFlowRuntime(r,'respawn');assert.equal(r.hitConfirm.active,false);assert.deepEqual(combatFlowDebug(r).control.pending,[]);});
test('runtime serial only advances for registered hit events',()=>{let r=createCombatFlowRuntime();const s=r.serial;r=registerCombatFlowHit(r,{damage:20});assert.equal(r.serial,s+1);});
test('debug surface summarizes without player/world serialization',()=>{const d=combatFlowDebug(createCombatFlowRuntime());assert.ok('control' in d);assert.ok('hitConfirm' in d);assert.equal('player' in d,false);assert.equal('world' in d,false);});
test('transition lock prevents buffered action release',()=>{const b=beginCombatFlowFrame(createCombatFlowRuntime(),raw(['heavy']),.016,{player:player(),attackData:lightData,transitionLocked:true});assert.equal(b.action,null);assert.ok(b.runtime.control.buffer.entries.heavy);});
test('threat focus can select an active enemy while control remains independent',()=>{const enemy={id:'e1',x:120,state:'windup',stateTime:.4,windup:.5,dead:false};const b=beginCombatFlowFrame(createCombatFlowRuntime(),raw(),.016,{player:{...player(),x:0},enemies:[enemy]});assert.equal(b.runtime.focus.threat.target.id,'e1');assert.equal(b.runtime.control.leased,null);});
